name: Test Single Pkg Workflow

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: 'build type, d or p'
        default: 'd'
      quals:
        description: 'qualifiers'
        default: 's128:e20'

jobs:

  build_single_pkg:
    name: test single pkg
    uses: art-daq/.github/.github/workflows/artdaq-test-single-pkg.yml@stable